# Generated by Django 4.1.13 on 2025-04-01 17:14

import django.contrib.auth.models
import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('contact', models.CharField(max_length=100, verbose_name='Contact Information')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email Address')),
                ('address', models.TextField(blank=True, verbose_name='Physical Address')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Department Name')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
            ],
            options={
                'verbose_name': 'Department',
                'verbose_name_plural': 'Departments',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('phone', models.CharField(blank=True, max_length=20, verbose_name='Phone Number')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='employees', to='erp.department', verbose_name='Department')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='employee_set', related_query_name='employee', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='employee_set', related_query_name='employee', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Employee',
                'verbose_name_plural': 'Employees',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_estimate_id', models.CharField(help_text='Reference ID from Bookkeeping System', max_length=20, unique=True, verbose_name='BK Estimate ID')),
                ('status', models.CharField(choices=[('draft', 'Draft (Sales)'), ('submitted', 'Submitted to CRM'), ('verified', 'Verified'), ('dispatched', 'Dispatched'), ('delivered', 'Delivered (Signed)')], default='draft', max_length=20, verbose_name='Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='estimates', to='erp.customer', verbose_name='Customer')),
                ('sales_agent', models.ForeignKey(limit_choices_to={'department__name': 'Sales'}, on_delete=django.db.models.deletion.PROTECT, related_name='sales_estimates', to='erp.employee', verbose_name='Sales Agent')),
            ],
            options={
                'verbose_name': 'Estimate',
                'verbose_name_plural': 'Estimates',
                'ordering': ['-created_at'],
                'permissions': [('change_estimate_status', 'Can modify estimate status'), ('view_all_estimates', 'Can view all estimates')],
            },
        ),
        migrations.CreateModel(
            name='SparePart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Part Name')),
                ('sku', models.CharField(help_text='Matching BK system SKU', max_length=50, unique=True, verbose_name='SKU')),
                ('current_stock', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Current Stock')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Unit Price')),
            ],
            options={
                'verbose_name': 'Spare Part',
                'verbose_name_plural': 'Spare Parts',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Verification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notes', models.TextField(blank=True, verbose_name='Verification Notes')),
                ('verification_date', models.DateTimeField(auto_now_add=True, verbose_name='Verification Date')),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='verification', to='erp.estimate', verbose_name='Estimate')),
                ('verified_by', models.ForeignKey(limit_choices_to={'department__name': 'Verification'}, on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Verified By')),
            ],
            options={
                'verbose_name': 'Verification',
                'verbose_name_plural': 'Verifications',
                'ordering': ['-verification_date'],
            },
        ),
        migrations.CreateModel(
            name='StoresReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discrepancies', models.TextField(blank=True, verbose_name='Discrepancy Notes')),
                ('reconciliation_date', models.DateTimeField(auto_now_add=True, verbose_name='Reconciliation Date')),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliation', to='erp.estimate', verbose_name='Estimate')),
                ('reconciled_by', models.ForeignKey(limit_choices_to={'department__name': 'Stores'}, on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Reconciled By')),
            ],
            options={
                'verbose_name': 'Stores Reconciliation',
                'verbose_name_plural': 'Stores Reconciliations',
                'ordering': ['-reconciliation_date'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(max_length=200, verbose_name='Notification Message')),
                ('is_read', models.BooleanField(default=False, verbose_name='Read Status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='erp.estimate', verbose_name='Estimate')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='erp.employee', verbose_name='Recipient')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Dispatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bk_proforma_id', models.CharField(help_text='Reference ID from Bookkeeping System', max_length=20, verbose_name='BK Proforma ID')),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Transport Cost')),
                ('vehicle_number', models.CharField(max_length=20, verbose_name='Vehicle Number')),
                ('driver_name', models.CharField(max_length=100, verbose_name='Driver Name')),
                ('driver_contact', models.CharField(max_length=20, verbose_name='Driver Contact')),
                ('dispatch_time', models.DateTimeField(auto_now_add=True, verbose_name='Dispatch Time')),
                ('is_delivered', models.BooleanField(default=False, verbose_name='Delivery Status')),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dispatch', to='erp.estimate', verbose_name='Estimate')),
            ],
            options={
                'verbose_name': 'Dispatch',
                'verbose_name_plural': 'Dispatches',
                'ordering': ['-dispatch_time'],
            },
        ),
        migrations.CreateModel(
            name='DeliveryConfirmation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signed_document', models.FileField(upload_to='delivery_proofs/%Y/%m/%d/', verbose_name='Signed Delivery Note')),
                ('upload_time', models.DateTimeField(auto_now_add=True, verbose_name='Upload Time')),
                ('estimate', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_confirmation', to='erp.estimate', verbose_name='Estimate')),
                ('uploaded_by', models.ForeignKey(limit_choices_to={'department__name': 'Sales'}, on_delete=django.db.models.deletion.PROTECT, to='erp.employee', verbose_name='Uploaded By')),
            ],
            options={
                'verbose_name': 'Delivery Confirmation',
                'verbose_name_plural': 'Delivery Confirmations',
                'ordering': ['-upload_time'],
            },
        ),
        migrations.CreateModel(
            name='EstimateItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantity')),
                ('negotiated_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Negotiated Price')),
                ('estimate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.estimate', verbose_name='Estimate')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='erp.sparepart', verbose_name='Spare Part')),
            ],
            options={
                'verbose_name': 'Estimate Item',
                'verbose_name_plural': 'Estimate Items',
                'unique_together': {('estimate', 'part')},
            },
        ),
    ]
