# Generated by Django 4.1.13 on 2025-04-02 00:32

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('erp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliveryconfirmation',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliveryconfirmation',
            name='estimate',
        ),
        migrations.RemoveField(
            model_name='deliveryconfirmation',
            name='signed_document',
        ),
        migrations.RemoveField(
            model_name='deliveryconfirmation',
            name='upload_time',
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='customer_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='estimate_number',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='extracted_data',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='deliveryconfirmation',
            name='signed_image',
            field=models.ImageField(blank=True, upload_to='delivery_notes/%Y/%m/', validators=[django.core.validators.FileExtensionValidator(['jpg', 'png', 'jpeg'])]),
        ),
        migrations.AlterField(
            model_name='deliveryconfirmation',
            name='uploaded_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'groups__name': 'Sales'}, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
