# Generated by Django 4.1.13 on 2025-04-03 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0002_alter_deliveryconfirmation_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='estimate',
            field=models.CharField(max_length=20, null=True, verbose_name='Estimate'),
        ),
    ]
