# Generated by Django 4.1.13 on 2025-04-04 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0003_alter_dispatch_estimate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dispatch',
            name='is_delivered',
        ),
        migrations.AddField(
            model_name='dispatch',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Cancellation Reason'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='delivery_confirmation_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Delivery Confirmation Time'),
        ),
        migrations.AddField(
            model_name='dispatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('in_transit', 'In Transit'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20, verbose_name='Dispatch Status'),
        ),
        migrations.AlterField(
            model_name='dispatch',
            name='estimate',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Estimate'),
        ),
    ]
