# Generated by Django 4.1.13 on 2025-04-04 01:56

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0004_remove_dispatch_is_delivered_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estimate_number', models.CharField(help_text='The estimate number this delivery note belongs to', max_length=20, verbose_name='Estimate Number')),
                ('customer_name', models.CharField(max_length=100, verbose_name='Customer Name')),
                ('destination', models.CharField(max_length=200, verbose_name='Delivery Destination')),
                ('customer_remarks', models.TextField(blank=True, null=True, verbose_name='Customer Remarks')),
                ('sales_agent', models.CharField(max_length=100, verbose_name='Sales Agent Name')),
                ('signed_document', models.FileField(upload_to='delivery_notes/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'jpg', 'jpeg', 'png'])], verbose_name='Signed Delivery Note')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Upload Date')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Verified by Admin')),
            ],
            options={
                'verbose_name': 'Customer Delivery Note',
                'verbose_name_plural': 'Customer Delivery Notes',
                'ordering': ['-upload_date'],
            },
        ),
        migrations.DeleteModel(
            name='DeliveryConfirmation',
        ),
    ]
