# Generated by Django 4.1.13 on 2025-04-04 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0005_deliverynote_delete_deliveryconfirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estimate',
            name='customer',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='estimate',
            name='sales_agent',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
