# Generated by Django 4.1.13 on 2025-04-23 08:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0007_alter_customer_options_remove_customer_address_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Role Name')),
                ('description', models.TextField(blank=True, verbose_name='Role Description')),
            ],
            options={
                'verbose_name': 'Role',
                'verbose_name_plural': 'Roles',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='customer',
            name='business_billboard',
        ),
        migrations.AddField(
            model_name='customer',
            name='trading_license',
            field=models.ImageField(blank=True, null=True, upload_to='photos/license/'),
        ),
        migrations.AddField(
            model_name='employee',
            name='is_verified',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Verified by Admin'),
        ),
        migrations.AddField(
            model_name='employee',
            name='role',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='employee_role', to='erp.userrole', verbose_name='Role'),
        ),
    ]
