# Generated by Django 4.1.13 on 2025-04-26 12:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0008_userrole_remove_customer_business_billboard_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverynote',
            options={},
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='customer_name',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='customer_remarks',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='sales_agent',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='signed_document',
        ),
        migrations.RemoveField(
            model_name='deliverynote',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='customer_name_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='date_goods_received',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='date_of_delivery',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_date',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='extracted_text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='receiver_contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='sales_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='uploaded_image',
            field=models.ImageField(blank=True, null=True, upload_to='delivery_notes/'),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='warehouse',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='estimate_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='DeliveryNoteItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('s_no', models.IntegerField()),
                ('item_description', models.CharField(max_length=255)),
                ('quantity', models.FloatField()),
                ('delivery_note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='erp.deliverynote')),
            ],
        ),
    ]
