# Generated by Django 4.1.13 on 2025-04-26 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0009_alter_deliverynote_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynote',
            name='created_at',
        ),
    ]
