# Generated by Django 4.1.13 on 2025-04-28 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0010_remove_deliverynote_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliverynoteitem',
            name='s_no',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='created_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='updated_at',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='deliverynoteitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='date_goods_received',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='date_of_delivery',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynote',
            name='warehouse',
            field=models.CharField(blank=True, default='Main Location', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='deliverynoteitem',
            name='quantity',
            field=models.FloatField(default=1),
        ),
    ]
