# Generated by Django 4.1.13 on 2025-04-28 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0011_remove_deliverynoteitem_s_no_deliverynote_created_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='delivery_note_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
