# Generated by Django 4.1.13 on 2025-04-28 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0012_deliverynote_delivery_note_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
