# Generated by Django 4.1.13 on 2025-04-28 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('erp', '0013_deliverynote_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverynote',
            old_name='uploaded_image',
            new_name='image',
        ),
    ]
